services:
  db:
    image: mysql:8
    volumes: 
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin  
      MYSQL_DATABASE: invbot
      MYSQL_USER: invbot
      MYSQL_PASSWORD: invbot

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    ports:
     - '8888:8080'

volumes:
  mysql-data:
